config/routes.rb
Rails.application.routes.draw do
  devise_for :people, controllers:{registrations: 'people/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :addresses
  get 'books/viewallbooks'
  get 'orders/order_detail'
  get 'orders/view_person/:id'=>'orders#view_person', as: :view_person
  # get 'addresses/confirm_order'
  root to: 'books#index'
  get 'final_confirm/:id' => 'orders#final_confirm', as: :final_confirm
  get 'final_confirm_to_current_person/:id' => 'orders#final_confirm', as: :final_confirm_to_current_person
 
  get 'confirm_order/:id/' => 'addresses#confirm_order', as: :confirm_order
  get 'viewaddress/:id/' => 'addresses#viewaddress', as: :viewaddress
  get 'cities/:state', to: 'application#cities'

  get 'addresses/addnew'
  get 'addresses/change_city'
  get 'books/near_by_me' => 'books#near_by_me', as: :near_by_me
  resources :categories
  resources :books
  resources :addresses
  resources :orders
  resources :charges
  resources :notifications do
    collection do
      post :mark_as_read 
    end
  end
  
  resources :books do 
    resources :addresses do
      get 'confirm_order'
    end
  end
  



end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :book
  belongs_to :person
  belongs_to :address
  enum order_status:[:placed,:confirmed]
  enum paymentStatus:[:pending,:paid]
end

app/controllers/orders_controller.rb
  class OrdersController < ApplicationController
    layout "devicelayout"
  def new
    @order=Order.create
  end
  def create
    @book=Book.find(params[:order][:book_id])
    @address=Address.find(order_params[:address_id])
    @order = Order.new(order_params)
    @order.person_id=current_person.id
    @order.order_status=0  
    @order.paymentStatus=0 
    if @order.save
      Notification.create(recipient: @book.person, actor: current_person, action: "Your book wants to buy", notifiable: @book)

    end
    @book.status=0
    @book.save 
    redirect_to books_path
  end 
  def view_person
    @person=Person.find(params[:id])
  end
  def index
    @orders=Order.where(person_id: current_person.id)
    @count=@orders.count
  end
  def show
    @book=Book.find(params[:id])
    @order=Order.find_by(book_id: @book.id)
  end
  def destroy
    @order=Order.find(params[:id])
    @book=@order.book
    @book.status=true
    @book.save
    @order.destroy
    redirect_to orders_path
  end


  def order_detail
    @address=Address.find(params[:address_id])
    @book=Book.find(params[:id])
    @address=Address.find(order_params[:address_id])
  end

  def confirm_order
    @book=Book.find(order_params[:book_id])
  end

  def final_confirm
    @order=Order.find(params[:id])
    @order.order_status=1
    @code=SecureRandom.hex(10)
    @order.confirmationCode=@code
    @order.save
    PersonMailer.confirm_order_email(@order.person,@code).deliver_now
    PersonMailer.confirm_order_email(current_person,@code).deliver_now
    redirect_to  books_viewallbooks_path 
  end


  private
  def order_params
    params.require(:order).permit(:person_id,:book_id,:address_id)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<div class="boxed-section request-form">
  <h2 class="section-title text-center">Order Detail</h2>
  <table border="1">
    <tr>
      <th>Serial number</th>
      <th>Book Name</th>
      <th>View Book Detail</th>
      <th>View Order Detail </th>
      <th>View Person Detail</th>
      <th>status</th> 
      <th>cancel</th>
      <th>payment</th>
    </tr>
    <% @orders.each_with_index do |order, index| %>     
      <tr>
        <td><%= index+1 %></td>
        <td><%= order.book.book_name%></td>
        <td><%= link_to "view book detail",  book_path(order.book) %></td>
        <td><%= link_to "view address detail", address_path(order.address)%></td>
        <td><%= link_to "view person detail",view_person_path(order.person)%></td>
        <td><%=order.order_status%>
        <td><%= link_to "cancel order" ,order_path(order), method: :delete %>
        <%if order.order_status == "confirmed"%>
          <%if order.paymentStatus == "paid"%>
            <td>already paid</td>
          <%else%>
            <td> 
              <%= form_tag charges_path(:charges => { :order_id => order.id }), method: :post do %>
                <article>
                  <% if flash[:error].present? %>
                    <div id="error_explanation">
                      <p><%= flash[:error] %></p>
                    </div>
                  <% end %>
                  
                </article>
                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="A month's subscription"
                data-amount=<%=order.book.book_price_for_rent.to_i%>
                data-locale="auto"></script>
              <%end%>
            </td>
          <%end%>
        <%else%>
          <td>Not Confirmed</td>
        <%end%>
      </tr>      
    <%end%>
  </table>
</div>

app/views/orders/order_detail.html.erb
<p>Details of Person</p>
<p>Details of book</p>

app/views/orders/show.html.erb
<h2 class="section-title text-center">Book Detail </h2>
<% if @order.order_status=="placed"%>
  <%= link_to "confirm" ,final_confirm_path(@order.id)%>
<%else%>
  <p>You can alredy confirm the order</p>
  <%= link_to "cancel order" , order_path(@order), method: :delete %>
<%end%> 
<div class="boxed-section request-form">
  <p>
    Book name:
    <%= @order.book.book_name %>
  </p>
  <p>
    Author name:
    <%= @order.book.author_name %>
  </p>
  <p>
    Book price:
    <%= @order.book.book_price %>
  </p>
  <p>
    Book language:
    <%= @order.book.book_language %>
  </p>
  <p>
    Book publish year:
    <%= @order.book.book_publish_year %>
  </p>
  <p>
    Book publisher_name:
    <%= @order.book.book_publisher_name %>
  </p>
  <p>
    Book price_for_rent:
    <%= @order.book.book_price_for_rent %>
  </p>
  <p>
    Duration of giving book:
    <%= @order.book.duration_of_giving_book %>
  </p>
   <p>
    category name
    <%= Category.find(@order.book.category_id).category_name %>
  </p>
</div>
<h2 class="section-title text-center">Address detail</h2>
<div class="boxed-section request-form">
  <p>
    Full Name:
    <%= @order.address.full_name %>
  </p>
  <p>
    Address Line 1
    <%= @order.address.address_line1 %>
  </p>
  <p>
    Address Line 2:
    <%= @order.address.address_line2 %>
  </p>
  <p>
    City:
    <%= @order.address.city %>
  </p>
  <p>
    State:
    <%= @order.address.state %>
  </p>
  <p>
    Country:
    <%= @order.address.country %>
  </p>
  <p>
    Pincode:
    <%=@order.address.pincode %>
  </p>
</div>
<h2 class="section-title text-center">Person detail</h2>
<div class="boxed-section request-form">
  <p>
    name:
    <%= @order.person.user_name %>
  </p>
  <p>
    email id:
    <%= @order.person.email%>
  </p>
  <p>
    Address Line 2:
    <%= @order.address.address_line2 %>
  </p>
  <p>
    Gender:
    <%= @order.person.gender %>
  </p>
  <p>
    Contact number:
    <%= @order.person.contact_number %>
  </p>
</div>

app/views/orders/view_person.html.erb
<h2 class="section-title text-center">Person detail</h2>
<div class="boxed-section request-form">
  <p>
    name:
    <%= @person.user_name %>
  </p>
  <p>
    email id:
    <%= @person.email%>
  </p>
  <p>
    Gender:
    <%= @person.gender %>
  </p>
  <p>
    Contact number:
    <%= @person.contact_number %>
  </p>
</div>