config/routes.rb
Rails.application.routes.draw do
  devise_for :people, controllers:{registrations: 'people/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :addresses
  get 'books/viewallbooks'
  get 'orders/order_detail'
  get 'orders/view_person/:id'=>'orders#view_person', as: :view_person
  # get 'addresses/confirm_order'
  root to: 'books#index'
  get 'final_confirm/:id' => 'orders#final_confirm', as: :final_confirm
  get 'final_confirm_to_current_person/:id' => 'orders#final_confirm', as: :final_confirm_to_current_person
 
  get 'confirm_order/:id/' => 'addresses#confirm_order', as: :confirm_order
  get 'viewaddress/:id/' => 'addresses#viewaddress', as: :viewaddress
  get 'cities/:state', to: 'application#cities'

  get 'addresses/addnew'
  get 'addresses/change_city'
  get 'books/near_by_me' => 'books#near_by_me', as: :near_by_me
  resources :categories
  resources :books
  resources :addresses
  resources :orders
  resources :charges
  resources :notifications do
    collection do
      post :mark_as_read 
    end
  end
  
  resources :books do 
    resources :addresses do
      get 'confirm_order'
    end
  end
  



end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :person
  belongs_to :category
  belongs_to :address
  validates :book_name, :author_name, :book_price, :book_language, :book_publish_year, :book_publisher_name, :book_price_for_rent, :duration_of_giving_book, presence: true
  mount_uploader :bookImage, BookImageUploader
  def self.search(search,author_search,category="-1")
    if(category=="-1")
       self.where("book_name like ? and author_name like ?", "%#{search}%", "%#{author_search}%")
    else
      if search || author_search ||category
        self.where("book_name like ? and author_name like ? and category_id=#{category}", "%#{search}%", "%#{author_search}%")  
      else
        self.all
      end
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_person!
  layout "devicelayout"
  def new
    @book=Book.new
    @addresses=Address.where(person_id:current_person.id)
  end
  def create
    @category=Category.find(params[:book][:category_id])
    @person=Person.find_by(params[:book][:person_id]) 
    @book=@category.books.create(book_params)
    @addresses=Address.where(person_id:current_person.id)
    @book.person_id=current_person.id
    if @book.save
      redirect_to books_viewallbooks_path
    else
      render 'new'
    end   
  end
  def viewallbooks
    @books=Book.where(person_id:current_person.id)
  end
  def show
    @book=Book.find(params[:id])
  end
  def index
    @books=Book.where(status: true)
    # @first_book=@books.first.category_id
=begin
    if params[:category]==nil
      @cat=Category.find(@first_book)
    else
=end
    if params[:category]==nil
      @books=Book.where(status: true)
    else
      if(params[:category]=="all")
        @books=Book.where(status: true)
        @books=@books.search(params[:search],params[:author_search])
      
      else
        @cat=Category.find_by(category_name: params[:category]) 
        @books=@books.search(params[:search],params[:author_search],@cat.id)
    
      end
    end
    #@books=Book.where(person_id:current_person.)
  end
  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    redirect_to  books_viewallbooks_path 
  end
  def edit
    @book=Book.find(params[:id])
  end
  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path
    else
      render 'edit'
    end
  end
  def near_by_me
    @address_of_current_person=Address.where(person_id: current_person.id).last
    @books=Book.where(status: true)
    @bookadress=@books.pluck(:address_id)
    @arr=Array.new
    @bookadress.each do |address|
      @address=Address.find(address)
      @arr<<@address
    end

    @a=Array.new
    #@arr=@arr.uniq
    @arr.each do |i|
       b= @address_of_current_person.distance_to([i.latitude,i.longitude])  
       @a.push(b)
    end
    distance=Hash.new
    len=@arr.length
    len.times do |i|
      @add=@arr[i].id
      distance[@add] = @a[i]
    end
    distance=distance.sort {|a,b| a[1]<=>b[1]}
    @books_array=Array.new 
    distance.each do |i|
      @books_array.push(@books.where(address_id: i[0]))
    end
  
  

    #

  end



=begin
  def flatten_array(nested_array, initial=[])
    nested_array.each do |item|
      if item.kind_of?(Array)
        flatten_array(item, initial)
      else
        exit
        initial.push item

      end
    end
    initial
    exit
  end
=end

# Example of use
  private
  def book_params
    params.require(:book).permit(:book_name, 
                                :author_name, 
                                :book_price, 
                                :book_language, 
                                :book_publish_year,
                                :book_publisher_name,
                                :book_price_for_rent,
                                :duration_of_giving_book,
                                :person_id,
                                :category_id,
                                :address_id,
                                :search,
                                :author_search,
                                :bookImage)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="col-md-6"> 
  <div class="boxed-section request-form">
    <h2 class="section-title text-center">Edit Book</h2>
    <%= form_for @book do |form|%>
      <% if @book.errors.any? %>
        <div id="error_explanation">
           <h2><%= pluralize(@book.errors.count, "error") %> prohibited this message from being saved:</h2>
           <ul>
             <% (@book.errors.full_messages).each do |msg| %>
             <% #Should have been: @location.errors.full_messages.each do |msg| %>
             <li>
               <%= msg %>
             </li>
             <% end %>
           </ul>
        </div>
      <% end %>
      <%=form.label :book_name %>
      <%=form.text_field :book_name%>

      <%=form.label :author_name %>
      <%=form.text_field :author_name%>

      <%=form.label :book_price %>
      <%=form.text_field :book_price%>

      <%=form.label :category %>
      <%category_array=Category.all.map{|category| [category.category_name]} %>
        <%=form.collection_select:category_id,Category.order(:id),:id,:category_name %>

      <%=form.label :book_language %>
      <%=form.text_field :book_language%>

      <%=form.label :book_publish_year %>
      <%=form.date_field :book_publish_year%>

      <%=form.label :book_publisher_name %>
      <%=form.text_field :book_publisher_name%>

      <%=form.label :duration_of_giving_book %>
      <%=form.date_field :duration_of_giving_book %>

      <%=form.label :book_price_for_rent %>
      <%=form.text_field :book_price_for_rent %>

      <%=form.label :Image_of_book %>
      <%= form.file_field :bookImage, id: :picture_image %>

      <%= form.submit %>

    <%end%>
  </div>
</div>

app/views/books/index.html.erb
<div class="boxed-section request-form" >
    <h2 class="section-title text-center">View books</h2>
    <p>    
      <%= form_tag  books_path , :method => 'get' do %>
        <%= label_tag :seach_by_book_name%>
        <%category_array= Category.all.map{|category| [category.category_name]}%>
        <%category_array=category_array.push("all")%>
        <%= select_tag "category", options_for_select(category_array), { "style" => "width:200px"} %>


        
          <%= label_tag :seach_by_book_name%>
          <%= text_field_tag :search, params[:search], options = {style:"width:200px"} %>
      
          <%= label_tag :seach_by_author_name%>
          <%= text_field_tag :author_search, params[:author_search], options = {style:"width:200px"} %>
          <%= submit_tag("search", :style => "width:100px;") %>
        <%end%>
    </p>
    <%= button_to "near me",  near_by_me_path , method: :get, style:"width:200px"  %>
    <table border="1">
      <tr>
        <th>Book name</th>
        <th>author name</th>
        <th>book_price</th>
        <th>category</th>
        <th>book language</th>
        <th>book publish year</th>
        <th>book publisher name</th>
        <th>duration of giving_book</th>
        <th>Book price for rent</th>
        <th>Buy</th>
    </tr>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.book_name%></td>
        <td><%= book.author_name%></td>
        <td><%= book.book_price%></td>
        <td><%= Category.find(book.category_id).category_name%></td>
        <td><%= book.book_language%></td>
        <td><%= book.book_publish_year%></td>
        <td><%= book.book_publisher_name%></td>
        <td><%= book.duration_of_giving_book%></td>
        <td><%= book.book_price_for_rent%></td>
        <td><%= link_to 'Buy', viewaddress_path(book) %></td>
      </tr>
    <%end%>
  </table>
</div>

app/views/books/near_by_me.html.erb
<div class="boxed-section request-form" >
  <h2 class="section-title text-center">View books</h2>
   <p>    
      <%= form_tag  books_path , :method => 'get' do %>
        <%= label_tag :seach_by_book_name%>
        <%category_array= Category.all.map{|category| [category.category_name]}%>
        <%category_array=category_array.push("all")%>
        <%= select_tag "category", options_for_select(category_array), { "style" => "width:200px"} %>


        
          <%= label_tag :seach_by_book_name%>
          <%= text_field_tag :search, params[:search], options = {style:"width:200px"} %>
      
          <%= label_tag :seach_by_author_name%>
          <%= text_field_tag :author_search, params[:author_search], options = {style:"width:200px"} %>
          <%= submit_tag("search", :style => "width:100px;") %>
        <%end%>
    </p>
  <%= button_to "near me",  near_by_me_path , method: :get, style:"width:200px"  %>
  <table border="1">
    <tr>
      <th>Book name</th>
      <th>author name</th>
      <th>book_price</th>
      <th>category</th>
      <th>book language</th>
      <th>book publish year</th>
      <th>book publisher name</th>
      <th>duration of giving_book</th>
      <th>Book price for rent</th>
      <th>Buy</th>
   </tr>
    <% @books_array.each do |book|%>
      <%book.each do |book|%>
        <tr>
          <td><%= book.book_name%></td>
          <td><%= book.author_name%></td>
          <td><%= book.book_price%></td>
          <td><%= Category.find(book.category_id).category_name%></td>
          <td><%= book.book_language%></td>
          <td><%= book.book_publish_year%></td>
          <td><%= book.book_publisher_name%></td>
          <td><%= book.duration_of_giving_book%></td>
          <td><%= book.book_price_for_rent%></td>
          <td><%= link_to 'Buy', viewaddress_path(book) %></td>
        </tr>
      <%end%> 
    <%end%>  
  </table>
</div>

app/views/books/new.html.erb
<div class="col-md-6"> 
  <div class="boxed-section request-form">
    <h2 class="section-title text-center">Create Book</h2>
    <%= form_for @book do |form|%>
      <% if @book.errors.any? %>
        <div id="error_explanation">
           <h2><%= pluralize(@book.errors.count, "error") %> prohibited this message from being saved:</h2>
           <ul>
             <% (@book.errors.full_messages).each do |msg| %>
             <% #Should have been: @location.errors.full_messages.each do |msg| %>
             <li>
               <%= msg %>
             </li>
             <% end %>
           </ul>
        </div>
      <% end %>
      <%=form.label :book_name %>
      <%=form.text_field :book_name%>

      <%=form.label :author_name %>
      <%=form.text_field :author_name%>

      <%=form.label :book_price %>
      <%=form.text_field :book_price%>

      <%=form.label :category %>
      <%category_array=Category.all.map{|category| [category.category_name]} %>
        <%=form.collection_select:category_id,Category.order(:id),:id,:category_name %>

      <%=form.label :book_language %>
      <%=form.text_field :book_language%>

      <%=form.label :book_publish_year %>
      <%=form.date_field :book_publish_year%>

      <%=form.label :book_publisher_name %>
      <%=form.text_field :book_publisher_name%>

      <%=form.label :duration_of_giving_book %>
      <%=form.date_field :duration_of_giving_book %>

      <%=form.label :book_price_for_rent %>
      <%=form.text_field :book_price_for_rent %>

      <%=form.label :Image_of_book %>
      <%= form.file_field :bookImage, id: :picture_image %>
  </div>

  <div class="boxed-section request-form"> 
    <h2 class="section-title text-center">View Addresses</h2>
    <table border="1">
      <tr>
        <th>Current Address</th>
        <th>Full Name:</th>
        <th>Address Line 1</th>
        <th>Address Line 2</th>
        <th>city</th>
        <th>state</th>
        <th>country</th>
        <th>Pincode</th>
     </tr>
     <% @addresses.each do |address| %>
      <tr>
        <td><%= form.radio_button :address_id, address.id %>  </td>
        <td><%= address.full_name%></td>
        <td><%= address.address_line1%></td>
        <td><%= address.address_line2%></td>
        <td><%= address.city%></td>
        <td><%= address.state%></td>
        <td><%= address.country%></td>
        <td><%= address.pincode%></td>
      </tr>
     <%end%>
    </table>
    <%= form.submit %>
  <%end%>
  </div>
</div>

app/views/books/show.html.erb
<div class="col-md-6"> 
  <div class="boxed-section request-form">
    <center>
    <h2 class="section-title text-center">Listing of Book</h2>
    <%= image_tag @book.bookImage , :size => "260x180" %></center>
    <p>Book name: <%= @book.book_name %> </p>
    <p>Author name: <%= @book.author_name %> </p>
    <p> Book price: <%= @book.book_price %> </p>
    <p> Book language: <%= @book.book_language %> </p>
    <p> Book publish year: <%= @book.book_publish_year %> </p>
    <p> Book publisher_name: <%= @book.book_publisher_name %> </p>
    <p> Book price_for_rent: <%= @book.book_price_for_rent %> </p>
    <p> Duration of giving book: <%= @book.duration_of_giving_book %> </p>
    <p> category name <%= Category.find(@book.category_id).category_name %> </p>
    <%= link_to "back",  books_path %>  </div>
</div>

app/views/books/viewalladdress.html.erb
<table border="1">
  <tr>
    <th>Current Address</th>
    <th>Full Name:</th>
    <th>Address Line 1</th>
    <th>Address Line 2</th>
    <th>city</th>
    <th>state</th>
    <th>country</th>
    <th>Pincode</th>
  </tr>
  <% @addresses.each do |address| %>
    <tr>
      <td><%= form.radio_button :address_id, address.id %>  </td>
      <td><%= address.full_name%></td>
      <td><%= address.address_line1%></td>
      <td><%= address.address_line2%></td>
      <td><%= address.city%></td>
      <td><%= address.state%></td>
      <td><%= address.country%></td>
      <td><%= address.pincode%></td>
    </tr>
  <%end%>
</table>

app/views/books/viewallbooks.html.erb
<h2 class="section-title text-center">View books</h2>
<%= link_to 'Add Book', new_book_path%>
  <table border="1">
    <tr>
      <th>Book Image</th>
      <th>Book name</th>
      <th>author name</th>
      <th>book_price</th>
      <th>category</th>
      <th>book language</th>
      <th>book publish year</th>
      <th>book publisher name</th>
      <th>duration of giving_book</th>
      <th>Book price for rent</th>
      <th>Show</th>
      <th>Edit</th>
      <th>delete</th>
      <th>Status</th>
      <th>Order detail</th>

   </tr>
   <% @books.each do |book| %>
    <tr>
      <td><%= image_tag book.bookImage , :size => "100x80" %></td>
      <td><%= book.book_name%></td>
      <td><%= book.book_name%></td>
      <td><%= book.book_price%></td>
      <td><%= Category.find(book.category_id).category_name%></td>
      <td><%= book.book_language%></td>
      <td><%= book.book_publish_year%></td>
      <td><%= book.book_publisher_name%></td>
      <td><%= book.duration_of_giving_book%></td>
      <td><%= book.book_price_for_rent%></td>
      <td><%= link_to 'show', book_path(book)%></td>
      <td><%= link_to 'Edit', edit_book_path(book)%></td>
      <td><%= link_to 'Delete', book_path(book),method: :delete%></td>
      <%if book.status==true%>
        <td>Buy</td>
      <%else%>
        <td>sold out</td>
      <%end%>
      <%if book.status==false%>
        <td><%= link_to "Order Detail", order_path(book)%></td>
      <%else%>
        <td></td>
      <%end%>
    </tr>
  <%end%>
</table>
  