config/routes.rb
Rails.application.routes.draw do
  devise_for :people, controllers:{registrations: 'people/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :addresses
  get 'books/viewallbooks'
  get 'orders/order_detail'
  get 'orders/view_person/:id'=>'orders#view_person', as: :view_person
  # get 'addresses/confirm_order'
  root to: 'books#index'
  get 'final_confirm/:id' => 'orders#final_confirm', as: :final_confirm
  get 'final_confirm_to_current_person/:id' => 'orders#final_confirm', as: :final_confirm_to_current_person
 
  get 'confirm_order/:id/' => 'addresses#confirm_order', as: :confirm_order
  get 'viewaddress/:id/' => 'addresses#viewaddress', as: :viewaddress
  get 'cities/:state', to: 'application#cities'

  get 'addresses/addnew'
  get 'addresses/change_city'
  get 'books/near_by_me' => 'books#near_by_me', as: :near_by_me
  resources :categories
  resources :books
  resources :addresses
  resources :orders
  resources :charges
  resources :notifications do
    collection do
      post :mark_as_read 
    end
  end
  
  resources :books do 
    resources :addresses do
      get 'confirm_order'
    end
  end
  



end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  layout "devicelayout"
  def new 
    @address=Address.new
  end
  def create
    @address=Address.new(address_params)
    @address.person_id= current_person.id
    if @address.save
      redirect_to address_path(@address)
    else
      render 'new'
    end  
  end
  def index
    @addresses=Address.where(person_id:current_person.id)
  end
  def addnew
    @address=Address.new
  end
  def viewaddress
    @addresses=Address.where(person_id:current_person.id)
    @book=Book.find(params[:id])
  end
  def show
    @address=Address.find(params[:id])
  end
  def edit
    @address=Address.find(params[:id])  
  end
  def update
    @address=Address.find(params[:id])
    if @address.update(address_params)
      redirect_to addresses_path
    else
      render 'edit'
    end
  end
  def destroy
    @address=Address.find(params[:id])
    @address.destroy
    redirect_to addresses_path 
  end
  def confirm_order
    @address=Address.find(params[:address_id])
    @book=Book.find(params[:book_id])
    @sellerDetail=@book.person
    @sellerAddressDetail=@book.address
  end
  def change_city
    params[:state]
    @state = CS.states(:in).key(params[:state])
  end
  private
  def address_params
    params.require(:address).permit(:full_name,
                                    :address_line1, 
                                    :address_line2, 
                                    :city, 
                                    :state, 
                                    :country, 
                                    :pincode, 
                                    :person_id)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_addaddress.html.erb
<%= form_for @address ,method: :post do |form|%>
  <% if @address.errors.any? %>
    <div id="error_explanation">
       <h2><%= pluralize(@address.errors.count, "error") %> prohibited this message from being saved:</h2>
       
       <ul>
         <%if(@address.errors.full_messages).each do |m|%> 
         <li>
           <%=m %>
         </li>
         <% end %>
         <%end%>
       </ul>
    </div>
  <% end %>
  <%= form.label :Full_name%>
  <%= form.text_field :full_name%>

  <%= form.label :Address_line_1%>
  <%= form.text_field :address_line1%>

  <%= form.label :Address_line_1%>
  <%= form.text_field :address_line2%>

  <%= form.label :state%>
  <%= form.select :state, CS.states(:in)%>

  <div id='city-list' remote: true>
    <%= render partial: 'city_list'%> <%#= f.text_field :city %> 
  </div>
  <%= form.label :country%>
  <%= form.text_field :country%>      
  <%= form.label :pincode%>
  <%= form.text_field :pincode%>
  <%= form.submit%>
<%end%>

app/views/addresses/_addnewaddress.html.erb
<div class="col-md-6"> 
  <div class="boxed-section request-form">
    <%= link_to "view Address", addresses_path %>
    <h2 class="section-title text-center">Enter Your Address</h2>
      <%= form_for @address ,method: :post do |form|%>
      <% if @address.errors.any? %>
        <div id="error_explanation">
           <h2><%= pluralize(@address.errors.count, "error") %> prohibited this message from being saved:</h2>
           
           <ul>
             <%if(@address.errors.full_messages).each do |m|%> 
             <li>
               <%=m %>
             </li>
             <% end %>
             <%end%>
           </ul>
        </div>
      <% end %>
      <%= form.label :Full_name%>
      <%= form.text_field :full_name%>

      <%= form.label :Address_line_1%>
      <%= form.text_field :address_line1%>

      <%= form.label :Address_line_1%>
      <%= form.text_field :address_line2%>

      <%= form.label :state%>
      <%= form.select :state, CS.states(:in)%>

      <div id='city-list' remote: true>
        <%= render partial: 'city_list'%> <%#= f.text_field :city %> 
      </div>
      <%= form.label :country%>
      <%= form.text_field :country%>      
      <%= form.label :pincode%>
      <%= form.text_field :pincode%>
      <%= form.submit%>
    <%end%>

  </div>
</div>

app/views/addresses/_city_list.html.erb
<% st =  defined?(state) ? state : :gj %>
<%= label_tag :city %><br />
<%= select_tag "address[city]", options_for_select(CS.cities(st, :in)), id: 'address_city' %>

app/views/addresses/_viewaddress.html.erb
<table border="1">
  <tr>
    <th>Full Name:</th>
    <th>Address Line 1</th>
    <th>Address Line 2</th>
    <th>city</th>
    <th>state</th>
    <th>country</th>
    <th>Pincode</th>
 </tr>
 <% @addresses.each do |address| %>
    <tr>
      <td><%= address.full_name%></td>
      <td><%= address.address_line1%></td>
      <td><%= address.address_line2%></td>
      <td><%= address.city%></td>
      <td><%= address.state%></td>
      <td><%= address.country%></td>
      <td><%= address.pincode%></td>
      <td><%= link_to "show", address_path(address)%></td>
      <td><%= link_to "edit", edit_address_path(address)%></td>
      <td><%= link_to "delete", address_path(address), method: :delete %></td> 
      <td><%= link_to "confirm order",  address_path(address) %></td>
    </tr>
  <%end%>
</table>

app/views/addresses/addnew.html.erb
<div class="col-md-6"> 
  <div class="boxed-section request-form">
    <%= link_to "view Address", addresses_path %>
    <h2 class="section-title text-center">Enter Your Address</h2>
    <%= render "addaddress"%>
  </div>
</div>

app/views/addresses/change_city.js.erb
$("#city-list").html("<%= escape_javascript(render partial: 'city_list', locals: {state: @state})%>")

app/views/addresses/confirm_order.html.erb
` <h1>Details Of Book and Address</h1>
  <h3>
    <%=link_to 'confirm order',orders_path(:order => { :book_id => @book.id, :address_id => @address.id }), method: :post %>
    <%= link_to 'cancel', books_path%></h3>
    <h1>Buyer Detail</h1>
    <div class="col-md-6"> 
      <div class="boxed-section request-form">
    <h2 class="section-title text-center">Book Detail</h2>
    <p> Book name: <%= @book.book_name %> </p>
    <p> Author name: <%= @book.author_name %> </p>
    <p> Book price: <%= @book.book_price %> </p>
    <p> Book language: <%= @book.book_language %> </p>
    <p> Book publish year: <%= @book.book_publish_year %> </p>
    <p> Book publisher_name: <%= @book.book_publisher_name %> </p>
    <p> Book price_for_rent: <%= @book.book_price_for_rent %> </p>
    <p> Duration of giving book: <%= @book.duration_of_giving_book %> </p>
    <p> category name <%= Category.find(@book.category_id).category_name %> </p>
    <br>
  </div>
</div>

<div class="col-md-6"> 
  <div class="boxed-section request-form">
    <h2 class="section-title text-center">Address Detail</h2>
    <p>Full Name: <%= @address.full_name %> </p>
    <p>Address Line 1: <%= @address.address_line1 %></p>
    <p>Address Line 2: <%= @address.address_line2 %></p>
    <p>City: <%= @address.city %> </p>
    <p>State: <%= @address.state %> </p>
    <p>Country:<%= @address.country %></p>
    <p>Pincode:<%= @address.pincode %></p> 
  </div>
</div>

<h1>seller Detail</h1>
<div class="col-md-6"> 
  <div class="boxed-section request-form">
    <h2 class="section-title text-center">Person detail</h2> 
    <p>name:<%= @sellerDetail.user_name %></p>
    <p>email id:<%= @sellerDetail.email%></p>
    <p>Gender:<%= @sellerDetail.gender %></p>
    <p>Contact number:<%= @sellerDetail.contact_number %></p> 
  </div>
</div>


<div class="col-md-6"> 
  <div class="boxed-section request-form">
    <h2 class="section-title text-center">Address Detail</h2>
    <p>Full Name:<%= @sellerAddressDetail.full_name %></p>
    <p>Address Line 1:<%= @sellerAddressDetail.address_line1 %></p>
    <p>Address Line 2:<%= @sellerAddressDetail.address_line2 %></p>
    <p>City:<%= @sellerAddressDetail.city %></p>
    <p>State:<%= @sellerAddressDetail.state %></p>
    <p>Country:<%= @sellerAddressDetail.country %></p>
    <p>Pincode:<%= @sellerAddressDetail.pincode %></p>
    <br>
    <br> 
  </div>
</div>

app/views/addresses/edit.html.erb
<div class="col-md-6"> 
  <div class="boxed-section request-form">
    <%= link_to "view Address", addresses_path %>
    <h2 class="section-title text-center">Enter Your Address</h2>
<%= form_for @address do |form|%>
  <% if @address.errors.any? %>
    <div id="error_explanation">
       <h2><%= pluralize(@address.errors.count, "error") %> prohibited this message from being saved:</h2>
       
       <ul>
         <%if(@address.errors.full_messages).each do |m|%> 
         <li>
           <%=m %>
         </li>
         <% end %>
         <%end%>
       </ul>
    </div>
  <% end %>
  <%= form.label :Full_name%>
  <%= form.text_field :full_name%>

  <%= form.label :Address_line_1%>
  <%= form.text_field :address_line1%>

  <%= form.label :Address_line_1%>
  <%= form.text_field :address_line2%>

  <%= form.label :state%>
  <%= form.select :state, CS.states(:in)%>

  <div id='city-list' remote: true>
    <%= render partial: 'city_list'%> <%#= f.text_field :city %> 
  </div>
  <%= form.label :country%>
  <%= form.text_field :country%>      
  <%= form.label :pincode%>
  <%= form.text_field :pincode%>
  <%= form.submit%>
<%end%>

  </div>
</div>

app/views/addresses/index.html.erb
<div class="boxed-section request-form"> 
  <%=link_to "add another address", new_address_path%>
  <h2 class="section-title text-center">View Addresses</h2>
  <table border="1">
    <tr>
      <th>Full Name:</th>
      <th>Address Line 1</th>
      <th>Address Line 2</th>
      <th>city</th>
      <th>state</th>
      <th>Pincode</th>
      <th colspan="3">Operation</th>
   </tr>
   <% @addresses.each do |address| %>
    <tr>
      <td><%= address.full_name%></td>
      <td><%= address.address_line1%></td>
      <td><%= address.address_line2%></td>
      <td><%= address.city%></td>
      <td><%= address.state%></td>
      <td><%= address.pincode%></td>
      <td><%= link_to "show", address_path(address)%></td>
      <td><%= link_to "edit", edit_address_path(address)%></td>
      <td><%= link_to "delete", address_path(address), method: :delete %></td>
    </tr>
   <%end%>
  </table>
</div>

app/views/addresses/new.html.erb
<div class="col-md-6"> 
  <div class="boxed-section request-form">
    <%= link_to "view Address", addresses_path %>
    <h2 class="section-title text-center">Enter Your Address</h2>
    <%= render "addaddress"%>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function()
  {
    $("#address_state").on("change", function()
    {
      
      $.ajax({
        url: 'change_city',
        method: 'GET',
        data: 
        {
          state: $(this).val()
        }
      });
    });
  });
</script>

app/views/addresses/newaddressofseller.html.erb
<div class="col-md-6"> 
  <div class="boxed-section request-form">
    <h2 class="section-title text-center">Enter Your Address</h2>
    <%= render "addaddress"%>
  </div>
</div>

app/views/addresses/show.html.erb
<div class="col-md-6"> 
  <div class="boxed-section request-form">
    <h2 class="section-title text-center">Listing of Category</h2>
    <p>Full Name:<%= @address.full_name %></p>
    <p>Address Line 1:<%= @address.address_line1 %></p>
    <p>Address Line 2:<%= @address.address_line2 %></p>
    <p>City:<%= @address.city %></p>
    <p>State:<%= @address.state %></p>
    <p>Country:<%= @address.country %></p>
    <p>Pincode:<%= @address.pincode %></p>
    <%= link_to "back",  addresses_path %>
  </div>
</div>

app/views/addresses/viewaddress.html.erb
e<div class="col-md-6"> 
  <div class="boxed-section request-form"> 
    <h2 class="section-title text-center">View Addresses</h2>
    <table border="1">
      <tr>
        <th>Full Name:</th>
        <th>Address Line 1</th>
        <th>Address Line 2</th>
        <th>city</th>
        <th>state</th>
        <th>Pincode</th>
        <th colspan="3">operation</th>
        <th>Confirm order</th>
     </tr>
     <% @addresses.each do |address| %>
    
      <tr>
        <td><%= address.full_name%></td>
        <td><%= address.address_line1%></td>
        <td><%= address.address_line2%></td>
        <td><%= address.city%></td>
        <td><%= address.state%></td>
        <td><%= address.pincode%></td>
        <td><%= link_to "show", address_path(address)%></td>
        <td><%= link_to "edit", edit_address_path(address)%></td>
        <td><%= link_to "delete", address_path(address), method: :delete %></td>
        <td><%= link_to "confirm order", book_address_confirm_order_path(@book,address) %></td>
      </tr>
     <%end%>
    </table>
  </div>
</div>