config/routes.rb
Rails.application.routes.draw do
  devise_for :people, controllers:{registrations: 'people/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :addresses
  get 'books/viewallbooks'
  get 'orders/order_detail'
  get 'orders/view_person/:id'=>'orders#view_person', as: :view_person
  # get 'addresses/confirm_order'
  root to: 'books#index'
  get 'final_confirm/:id' => 'orders#final_confirm', as: :final_confirm
  get 'final_confirm_to_current_person/:id' => 'orders#final_confirm', as: :final_confirm_to_current_person
 
  get 'confirm_order/:id/' => 'addresses#confirm_order', as: :confirm_order
  get 'viewaddress/:id/' => 'addresses#viewaddress', as: :viewaddress
  get 'cities/:state', to: 'application#cities'

  get 'addresses/addnew'
  get 'addresses/change_city'
  get 'books/near_by_me' => 'books#near_by_me', as: :near_by_me
  resources :categories
  resources :books
  resources :addresses
  resources :orders
  resources :charges
  resources :notifications do
    collection do
      post :mark_as_read 
    end
  end
  
  resources :books do 
    resources :addresses do
      get 'confirm_order'
    end
  end
  



end

app/views/layouts/_header.html.erb
<!-- Google analytics Code -->
    <script>
      window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
      ga('create', 'UA-123139078-1', 'auto');
      ga('send', 'pageview');
    </script>
    <script async src='https://www.google-analytics.com/analytics.js'></script>
  <!-- End Google analytics Code -->

<div id="site-content">
      <header class="site-header">
        <div class="primary-header">
          <div class="container">
            <a href="index.html" id="branding">
              <%= image_tag("logo.png")%>
              <h1 class="site-title">BOOK RENATL SYSTEM</h1>
            </a> <!-- #branding -->
            
            <div class="main-navigation">
              <button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>
              <ul class="menu">
                <li class="menu-item current-menu-item"><a href="index.html">Home</a></li>
                <li class="menu-item"><a href="course.html">Courses</a></li>
                <li class="menu-item"><a href="student.html">Students</a></li>
                <li class="menu-item"><a href="event.html">Events</a></li>
                <li class="menu-item"><%= link_to 'signout', destroy_person_session_path , method: :delete %>
</li>
              </ul> <!-- .menu -->
            </div> <!-- .main-navigation -->

            <div class="mobile-navigation"></div>
          </div> <!-- .container -->
        </div> <!-- .primary-header -->

        <div class="home-slider">
          <div class="container">
            <div class="slider">
              <ul class="slides">
                <li>
                  <div class="slide-caption">
                    <h2 class="slide-title">I Love to learn! <br> Welcome back school!</h2>
                    <p>Perspiciatis unde omnis iste natus error sit voluptatem accusantium totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                    <a href="#" class="button primary large">Learn more</a>
                  </div>
                  <img src="dummy/kid.png" alt="">
                </li>
                <li>
                  <div class="slide-caption">
                    <h2 class="slide-title">I Love to Read! <br> Welcome back school!</h2>
                    <p>Perspiciatis unde omnis iste natus error sit voluptatem accusantium totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                    <a href="#" class="button primary large">Learn more</a>
                  </div>
                  <img src="dummy/kid.png" alt="">
                </li>
                <li>
                  <div class="slide-caption">
                    <h2 class="slide-title">I Love to Play! <br> Welcome back school!</h2>
                    <p>Perspiciatis unde omnis iste natus error sit voluptatem accusantium totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                    <a href="#" class="button primary large">Learn more</a>
                  </div>
                  <img src="dummy/kid.png" alt="">
                </li>
              </ul> <!-- .slides -->
            </div> <!-- .slider -->
          </div> <!-- .container -->
        </div> <!-- .home-slider -->
      </header>
    </div>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="site-content">
      <header class="site-header" >
        <div class="primary-header">
          <div class="container">
            <a href="index.html" id="branding">
              <%= image_tag 'logo.png'%>
              <h1 class="site-title">BOOK REANTAL</h1>
            </a> <!-- #branding -->
            <div id="google_translate_element"></div>

<script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
}
</script>

<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
      <!-- .main-navigation -->

            <div class="mobile-navigation"></div>

          </div> <!-- .container -->
          
        </div> <!-- .primary-header -->
<!-- .home-slider -->

      </header>
    <%= yield %>
    
    </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/devicelayout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </head>

  <body>
    <div id="site-content">
      <header class="site-header" >
        <div class="primary-header">
           <a href="index.html" id="branding">
              <%= image_tag 'logo.png'%>
              <h1 class="site-title">BOOK REANTAL</h1>
            </a>
          <div class="container">
            <!-- #branding -->
            
            <div class="main-navigation">
              <button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>

              <ul class="menu">
        


                <li class="menu-item current-menu-item"><%= link_to 'Buy', books_path %></a></li>
                <li class="menu-item"><%= link_to 'Add Book', books_viewallbooks_path %></a></li>
               
                <li class="menu-item"><%= link_to 'placed order', orders_path%></a></li>
                <%if current_person.has_role? :admin%>
                 <li class="menu-item"><%= link_to 'Add category' ,categories_path%></a></li>
                <%end%>
                 <li class="menu-item"><%= link_to 'Address' ,addresses_path%></a></li>
                 <li class="menu-item"><%= link_to 'Edit profile' ,edit_person_registration_path%></a></li>
                
                <li class="menu-item"><%= link_to 'Signout', destroy_person_session_path , method: :delete %></li>
                <li class="menu-item"><%= link_to 'view profile', view_person_path(current_person) %></li>

                <li class="menu-item"><%= link_to current_person.email %></li>
                            <div id="google_translate_element"></div>

<script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
}
</script>

<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
      <!-- .main-navigation -->
               

                <li data-behavior="notifications">
                
                  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <span class="glyphicon glyphicon-bell"><span data-behavior='unread-count'></span></span>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1" data-behavior="notification-items" >  
                
                  </ul>
                </div>
              </li>
              
              </ul> 
              <!-- .menu -->
            </div> <!-- .main-navigation -->

            <div class="mobile-navigation"></div>

          </div> <!-- .container -->
          
        </div> <!-- .primary-header -->
<!-- .home-slider -->
 
      </header>
    <%= yield %>
    
    </div>
  </body>
</html>

<script type="text/javascript">
var Notifications,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Notifications = (function() {
  function Notifications() {
    this.handleSuccess = bind(this.handleSuccess, this);
    this.notifications = $("[data-behavior='notifications']");
    if (this.notifications.length > 0) {
      this.setup();
    }
  }

  Notifications.prototype.setup = function() {
    return $.ajax({
      url: "/notifications.json",
      dataType: "JSON",
      method: "GET",
      success: this.handleSuccess
    });
  };






  Notifications.prototype.handleSuccess = function(data) {
    
    var items;
    items = $.map(data, function(notification) {
      return "<li><a class='dropdown-item' href='" + notification.url + "'>" + notification.action + " "+notification.actor +"</a></li>";
    });
    console.log(items) 
    $("[data-behavior='unread-count']").text(items.length);
    return $("[data-behavior='notification-items']").html(items);
  }
  return Notifications;

})();

jQuery(function() {
  return new Notifications;
});

// ---
// generated by coffee-script 1.9.2
</script>